export const FAIL_SEARCH_BRANDS  = "FAIL_SEARCH_BRANDS" 
export const SUCCESS_SEARCH_BRANDS  = "SUCCESS_SEARCH_BRANDS" 
export const GET_SEARCH_BRANDS  = "GET_SEARCH_BRANDS" 
export const CLEAR_SEARCH_BRANDS  = "CLEAR_SEARCH_BRANDS" 